### ISSUE TITLE
赞了

### ISSUE THREAD

**Issue by xp12047** [5ime/vue-page#2]
就是不知道日后如果你更新了，我该怎么更新呢？命令？小白一个请见谅。

**Comment by 5ime** [comment]
一般来说不会更新，因为只是个单页面没有更新的必要
如果更新的话直接删掉重新上传最新源码即可

**Comment by xp12047** [comment]
> 不需要更新，因为只是个单页面没有更新的必要， 如果更新的话就可以删除升级最新的原始码

谢谢
